### PR TITLE
allow #:command-char argument to scribble lexer

### PR DESCRIPTION
**Pull request by AlexKnauth**

### CODE REVIEW

**Comment by mflatt** [comment]
@robby: Do I remember correctly that DrRacket's syntax colorer will call `scribble-lexer` multiple times, so that the regular expressions here would be compiled multiple times with the additional argument?
If so, I think it makes sense to add a `make-scribble-lexer`layer, where `scribble-lexer` is the result of calling that function with `#\@`, and so on.

**Comment by rfindler** [comment]
Yes, I believe so. And I agree that currying is a good approach.

**Comment by AlexKnauth** [comment]
Ok, I changed it to use the currying approach with make-scribble-lexer and make-scribble-inside-lexer.

**Comment by mflatt** [comment]
Bumped version, added tests, added docs, and merged.
As it turns out, my first test was to use #\+ as the character, which broke some of the regexp constructions. I adjusted those constructions.

**Comment by AlexKnauth** [comment]
Oh, I hadn't thought of that.  But shouldn't it use `regexp-quote` instead to do that?

**Comment by AlexKnauth** [comment]
Otherwise won't it break for `\` and `^` for example? (and probably others I haven't thought of yet)

**Comment by mflatt** [comment]
I didn't think to try those; `\` seems to work and `^` fails. More tests and repairs would be welcome!

**Comment by mflatt** [comment]
I didn't use `regexp-quote` because I thought that it would be more complicated than dropping characters into "[...]", but I think I chose badly.

**Pull request closed without merging**
